export const PRIVACY_POLICY = `
Mercury プライバシーポリシー（最終統合・完全版）

第1条（基本方針および適用範囲）
当開発者は、提供するアプリケーション「Mercury」（以下「本アプリ」といいます。）において、ユーザーの個人情報の保護を最重要事項として位置付けます。
当開発者は、個人情報の保護に関する法律その他関連法令、各国規制（GDPR、CCPA等を含む）、およびGoogle API Services User Data Policyを遵守し、適法かつ公正な手段により情報を取得・利用・管理します。

また、以下の原則に基づき運用します：
● 目的限定原則
● データ最小化原則
● 透明性の確保
● 安全管理の徹底
本ポリシーは、本アプリにおけるすべての個人情報の取扱いに適用されます。

第2条（定義）
本ポリシーにおける用語は以下の通り定義します。
● 「個人情報」：特定の個人を識別できる情報
● 「ユーザーデータ」：ユーザーが本アプリに提供または生成するすべての情報
● 「Googleユーザーデータ」：Googleアカウント連携により取得される情報
● 「処理」：取得、保存、利用、削除等の一切の取扱い

第3条（収集する情報）
当開発者は以下の情報を収集します。
1. ユーザー行動データ
● 検索履歴、閲覧履歴
● 学習時間、教材登録情報
● 操作ログ、設定情報
2. 技術情報
● デバイス識別子（広告ID等）
● OS、ブラウザ、言語設定
● IPアドレス、アクセス日時
3. Cookieおよび類似技術
● セッション管理
● 利用状況分析
● 広告効果測定
4. 外部連携情報
● Google Driveアクセストークン
● API経由のメタデータ

第4条（Googleユーザーデータの特別規定）
本アプリはGoogle Drive連携機能を提供するにあたり、以下を厳守します。
1. 利用目的の厳格限定
Googleユーザーデータは以下の目的にのみ使用されます：
● ユーザーが指定したファイルの表示
● 本アプリ内での閲覧機能提供
※広告、分析、機械学習、第三者提供には一切利用しません。
2. 非保存原則（Non-retention）
● ファイル本体はサーバーに保存しません
● データは一時的処理のみ
● キャッシュも恒久保存しません
3. 人的アクセス制限
以下の場合を除き、人間がデータへアクセスすることはありません：
● ユーザーからの明示的なサポート依頼
● セキュリティ対応
● 法令対応
4. 第三者提供の禁止
Googleユーザーデータは以下を除き提供されません：
● 法令に基づく場合
● 明示的同意
5. セキュリティ管理
● OAuthトークンの安全管理
● HTTPS通信の強制
● 不正アクセス防止

第5条（利用目的）
収集した情報は以下の範囲で利用されます：
● サービス提供・維持・改善
● パーソナライズ
● 不正利用検知
● ユーザーサポート
● 統計分析（匿名化データのみ）
※目的外利用は行いません。

第6条（広告およびトラッキング）
本アプリは以下を利用します：
● Amazonアソシエイト
● 楽天アフィリエイト
● メルカリアンバサダー
これらはCookie等を利用する場合があります。ユーザーはブラウザ設定によりCookieを制御できます。

第7条（第三者提供）
以下を除き、個人情報を第三者に提供しません：
● 本人同意
● 法令要求
● 緊急保護

第8条（委託・外部処理）
以下の処理を外部委託する場合があります：
● クラウドインフラ
● 認証
● 分析
委託先は適切に監督されます。

第9条（データ保存期間）
1. 必要最小限の期間のみ保持
2. 不要データは削除または匿名化
3. 法令義務がある場合は保存

第10条（国際データ移転）
個人情報は国外に移転される場合があります。この場合、適切な保護措置を講じます。

第11条（安全管理措置）
当開発者は以下を実施します：
● SSL/TLS暗号化
● アクセス制御
● セキュリティ監査
● 不正アクセス防止
※完全な安全性は保証されません。

第12条（ユーザーの権利）
ユーザーは以下を行う権利を有します：
● 開示
● 訂正
● 削除
● 利用停止
● データポータビリティ

第13条（未成年）
未成年は保護者同意が必要です。

第14条（責任の限定）
当開発者は以下について責任を負いません：
● 外部サービス起因の問題
● ユーザーの管理不備
● 通信環境の問題

第15条（ポリシーの変更）
1. 本ポリシーは変更可能
2. 掲示時点で効力発生
3. 継続利用で同意

第16条（お問い合わせ）
問い合わせはアプリ内または開発者へ。
`;

export const PRIVACY_POLICY_EN = `
Mercury Privacy Policy (Consolidated Full Version)

Article 1 (Basic Policy and Scope)
The developer positions the protection of user personal information as the most important matter in the application "Mercury".
The developer complies with personal information protection laws, relevant regulations (including GDPR, CCPA, etc.), and the Google API Services User Data Policy, and collects, uses, and manages information through lawful and fair means.

Article 2 (Definitions)
- "Personal Information": Information that can identify a specific individual.
- "User Data": All information provided or generated by the user.
- "Google User Data": Information obtained through Google account linkage.

Article 3 (Information Collected)
1. User Action Data: Search history, study time, material logs, etc.
2. Technical Information: Device IDs, OS, Browser, IP address.
3. Cookies: Session management, usage analysis.
4. External Data: Google Drive access tokens and metadata.

Article 4 (Special Provisions for Google User Data)
1. Strict Limitation of Purpose: Used ONLY for displaying files and viewing within the App. No ads, AI training, or sales.
2. Non-retention: Files are NOT stored on servers; only temporary processing.
3. Access Control: No human access except for support, security, or legal requirements.
4. Third-party: No provision to third parties unless required by law.
5. Security: Managed via safe OAuth tokens and HTTPS.

Article 5 (Purpose of Use)
Used for service provision, personalization, fraud detection, and support. No use beyond stated purposes.

Article 6 (Advertising and Tracking)
Uses Amazon/Rakuten/Mercari affiliate systems. Cookies may be used and can be controlled by browser settings.

Article 7 (Third-Party Provision)
No provision to third parties except with consent, legal requirements, or emergencies.

Article 8 (Outsourcing)
Infrastructure, auth, and analytics may be outsourced under supervision.

Article 9 (Retention Period)
Stored only for minimum necessary period. Deleted or anonymized when unnecessary.

Article 10 (International Data Transfer)
Appropriate protection is ensured during cross-border transfers.

Article 11 (Security Measures)
Encryption (SSL/TLS), access control, and audits are implemented.

Article 12 (User Rights)
Rights for disclosure, correction, deletion, and data portability are respected.

Article 13 (Minors)
Requires parental consent.

Article 14 (Limitation of Liability)
Not liable for issues caused by external services, user negligence, or network environments.

Article 15 (Policy Changes)
Changes become effective once posted. Continued use constitutes agreement.

Article 16 (Inquiries)
Contact via the app or developer.
`;

export const TERMS_OF_SERVICE = `
Mercury 利用規約

第1条（適用および規約の構成）
1. 本利用規約（以下「本規約」といいます。）は、当開発者が提供するアプリケーション「Mercury」（以下「本アプリ」といいます。）の利用条件を定めるものです。
2. 本規約は、本アプリの利用に関する当開発者とユーザーとの間の一切の関係に適用されます。
3. 当開発者は、本規約のほかに、本アプリの利用に関して個別規定を定めることがあります。
4. 個別規定は本規約の一部を構成し、矛盾する場合は個別規定が優先されます。
5. ユーザーは利用開始により、本規約のすべてに同意したものとみなされます。

第2条（定義）
● 「コンテンツ」：テキスト、画像、動画、プログラム等
● 「ユーザー投稿情報」：ユーザーが保存・投稿したPDFや学習履歴等
● 「知的財産権」：著作権、特許権、商標権等

第3条（利用登録およびアカウント管理）
1. 登録申請が当開発者に承認された時点で契約成立。
2. 虚偽申請や過去の違反がある場合は登録を拒否。
3. アカウント管理は自己責任。不正利用の損害はユーザー負担。

第4条（サービス内容）
教材検索、学習データ管理、学習記録、その他追加機能を提供。

第5条（禁止事項）
スクレイピング、リバースエンジニアリング、不正アクセス、サーバー負荷行為、他者の権利侵害、無断転載・再配布。

第6条（違反時の措置）
違反時はアカウント停止やデータ削除を実施。損害賠償義務や法的措置も含みます。

第7条（知的財産権）
本アプリの権利は当開発者に帰属。ユーザー情報の権利はユーザーに留保（運営上必要な利用は許諾）。

第8条（データおよびバックアップ）
保存は保証されません。ユーザーは自己責任でバックアップを。

第9条（外部サービス）
外部サービス（アフィリエイト等）の取引はユーザー責任。トラブルに当開発者は関与しません。

第10条（サービスの変更・停止）
保守、障害、不可抗力等で停止可能。サービス終了も可能。

第11条（非保証）
正確性、有用性、継続性、エラーの不在等を保証しません。

第12条（責任制限）
責任は法令上許される最大限まで制限され、間接損害等は対象外。

第13条（プライバシー）
個人情報はプライバシーポリシーに従い処理。

第14条（規約変更）
自由に変更可能。掲載時点で有効。

第15条（契約の終了）
退会はいつでも可能。違反時は強制解約。

第16条（準拠法・管轄）
1. 日本法準拠
2. 専属管轄：当開発者所在地裁判所
`;

export const TERMS_OF_SERVICE_EN = `
Mercury Terms of Service

Article 1 (Application)
These terms govern the use of "Mercury". By using the App, you agree to all provisions set forth herein.

Article 2 (Definitions)
Concerns "Content", "User Provided Info", and "Intellectual Property Rights".

Article 3 (Registration)
Contract is formed upon approval. Users must manage account credentials responsibly.

Article 4 (Services)
Provides material search, study management, and record analysis.

Article 5 (Prohibitions)
Scraping, unauthorized access, reverse engineering, and redistribution are strictly prohibited.

Article 6 (Violations)
Account suspension or removal may occur upon violation. Full compensation for damages required.

Article 7 (Rights)
App rights belong to the developer. User keeps rights to their uploads but grants necessary usage rights for operation.

Article 8 (Backup)
No guarantee for data storage. Users should maintain their own backups.

Article 9 (External Services)
Third-party transactions are at the user's own risk.

Article 10 (Suspension)
Service may be suspended for maintenance, failures, or force majeure.

Article 11 (Disclaimer)
No warranty for accuracy, usefulness, or error-free continuous access.

Article 12 (Liability)
Liability is limited to the extent permitted by law; indirect damages are excluded.

Article 13 (Privacy)
Information is handled according to the Privacy Policy.

Article 14 (Changes)
Terms can be updated; changes take effect once posted.

Article 15 (Termination)
Users can withdraw anytime. Breach results in termination.

Article 16 (Jurisdiction)
Governed by Japanese law; exclusive jurisdiction of the developer's local court.
`;
