export const PRIVACY_POLICY = `
Mercury プライバシーポリシー（最終統合・完全版）

第1条（基本方針および適用範囲）
当開発者は、提供するアプリケーション「Mercury」（以下「本アプリ」といいます。）において、ユーザーの個人情報の保護を最重要事項として位置付けます。
当開発者は、個人情報の保護に関する法律その他関連法令、各国規制（GDPR、CCPA等を含む）、およびGoogle API Services User Data Policyを遵守し、適法かつ公正な手段により情報を取得・利用・管理します。

また、以下の原則に基づき運用します：
● 目的限定原則
● データ最小化原則
● 透明性の確保
● 安全管理の徹底
本ポリシーは、本アプリにおけるすべての個人情報の取扱いに適用されます。

第2条（定義）
本ポリシーにおける用語は以下の通り定義します。
● 「個人情報」：特定の個人を識別できる情報
● 「ユーザーデータ」：ユーザーが本アプリに提供または生成するすべての情報
● 「Googleユーザーデータ」：Googleアカウント連携により取得される情報
● 「処理」：取得、保存、利用、削除等の一切の取扱い

第3条（収集する情報）
当開発者は以下の情報を収集します。
1. ユーザー行動データ
● 検索履歴、閲覧履歴
● 学習時間、教材登録情報
● 操作ログ、設定情報
2. 技術情報
● デバイス識別子（広告ID等）
● OS、ブラウザ、言語設定
● IPアドレス、アクセス日時
3. Cookieおよび類似技術
● セッション管理
● 利用状況分析
● 広告効果測定
4. 外部連携情報
● Google Driveアクセストークン
● API経由のメタデータ

第4条（Googleユーザーデータの特別規定）
本アプリはGoogle Drive連携機能を提供するにあたり、以下を厳守します。
1. 利用目的の厳格限定
Googleユーザーデータは以下の目的にのみ使用されます：
● ユーザーが指定したファイルの表示
● 本アプリ内での閲覧機能提供
※広告、分析、機械学習、第三者提供には一切利用しません。
2. 非保存原則（Non-retention）
● ファイル本体はサーバーに保存しません
● データは一時的処理のみ
● キャッシュも恒久保存しません
3. 人的アクセス制限
以下の場合を除き、人間がデータへアクセスすることはありません：
● ユーザーからの明示的なサポート依頼
● セキュリティ対応
● 法令対応
4. 第三者提供の禁止
Googleユーザーデータは以下を除き提供されません：
● 法令に基づく場合
● 明示的同意
5. セキュリティ管理
● OAuthトークンの安全管理
● HTTPS通信の強制
● 不正アクセス防止

第5条（利用目的）
収集した情報は以下の範囲で利用されます：
● サービス提供・維持・改善
● パーソナライズ
● 不正利用検知
● ユーザーサポート
● 統計分析（匿名化データのみ）
※目的外利用は行いません。

第6条（広告およびトラッキング）
本アプリは以下を利用します：
● Amazonアソシエイト
● 楽天アフィリエイト
● メルカリアンバサダー
これらはCookie等を利用する場合があります。ユーザーはブラウザ設定によりCookieを制御できます。

第7条（第三者提供）
以下を除き、個人情報を第三者に提供しません：
● 本人同意
● 法令要求
● 緊急保護

第8条（委託・外部処理）
以下の処理を外部委託する場合があります：
● クラウドインフラ
● 認証
● 分析
委託先は適切に監督されます。

第9条（データ保存期間）
1. 必要最小限の期間のみ保持
2. 不要データは削除または匿名化
3. 法令義務がある場合は保存

第10条（国際データ移転）
個人情報は国外に移転される場合があります。この場合、適切な保護措置を講じます。

第11条（安全管理措置）
当開発者は以下を実施します：
● SSL/TLS暗号化
● アクセス制御
● セキュリティ監査
● 不正アクセス防止
※完全な安全性は保証されません。

第12条（ユーザーの権利）
ユーザーは以下を行う権利を有します：
● 開示
● 訂正
● 削除
● 利用停止
● データポータビリティ

第13条（未成年）
未成年は保護者同意が必要です。

第14条（責任の限定）
当開発者は以下について責任を負いません：
● 外部サービス起因の問題
● ユーザーの管理不備
● 通信環境の問題

第15条（ポリシーの変更）
1. 本ポリシーは変更可能
2. 掲示時点で効力発生
3. 継続利用で同意

第16条（お問い合わせ）
問い合わせはアプリ内または開発者へ。
`;

export const PRIVACY_POLICY_EN = `
Mercury Privacy Policy (Consolidated Full Version)

Article 1 (Basic Policy and Scope)
The developer positions the protection of user personal information as the most important matter in the application "Mercury".
The developer complies with personal information protection laws, relevant regulations (including GDPR, CCPA, etc.), and the Google API Services User Data Policy, and collects, uses, and manages information through lawful and fair means.

Article 2 (Definitions)
- "Personal Information": Information that can identify a specific individual.
- "User Data": All information provided or generated by the user.
- "Google User Data": Information obtained through Google account linkage.

Article 3 (Information Collected)
1. User Action Data: Search history, study time, material logs, etc.
2. Technical Information: Device IDs, OS, Browser, IP address.
3. Cookies: Session management, usage analysis.
4. External Data: Google Drive access tokens and metadata.

Article 4 (Special Provisions for Google User Data)
1. Strict Limitation of Purpose: Used ONLY for displaying files and viewing within the App. No ads, AI training, or sales.
2. Non-retention: Files are NOT stored on servers; only temporary processing.
3. Access Control: No human access except for support, security, or legal requirements.
4. Third-party: No provision to third parties unless required by law.
5. Security: Managed via safe OAuth tokens and HTTPS.

Article 5 (Purpose of Use)
Used for service provision, personalization, fraud detection, and support. No use beyond stated purposes.

Article 6 (Advertising and Tracking)
Uses Amazon/Rakuten/Mercari affiliate systems. Cookies may be used and can be controlled by browser settings.

Article 7 (Third-Party Provision)
No provision to third parties except with consent, legal requirements, or emergencies.

Article 8 (Outsourcing)
Infrastructure, auth, and analytics may be outsourced under supervision.

Article 9 (Retention Period)
Stored only for minimum necessary period. Deleted or anonymized when unnecessary.

Article 10 (International Data Transfer)
Appropriate protection is ensured during cross-border transfers.

Article 11 (Security Measures)
Encryption (SSL/TLS), access control, and audits are implemented.

Article 12 (User Rights)
Rights for disclosure, correction, deletion, and data portability are respected.

Article 13 (Minors)
Requires parental consent.

Article 14 (Limitation of Liability)
Not liable for issues caused by external services, user negligence, or network environments.

Article 15 (Policy Changes)
Changes become effective once posted. Continued use constitutes agreement.

Article 16 (Inquiries)
Contact via the app or developer.
`;

export const TERMS_OF_SERVICE = `
Mercury 利用規約

制定日：2026年10月5日

第1条（適用）
1. 本利用規約（以下「本規約」という。）は、運営者が提供する学習管理アプリ「Mercury」（以下「本アプリ」という。）の利用条件を定めるものである。
2. 本規約は、本アプリを利用するすべての者（以下「ユーザー」という。）に適用される。
3. 運営者が本アプリ上で別途定める注意事項、ガイドラインその他の規定は、本規約の一部を構成する。本規約と矛盾する場合は、当該規定が優先する。

第2条（利用の開始）
1. ユーザーは、Googleアカウントでログインし、本規約に同意したうえで、本アプリの利用を開始するものとする。
2. ログインして利用を開始した時点で、ユーザーは本規約に同意したものとみなす。
3. 未成年者は、保護者の同意を得たうえで利用すること。

第3条（サービス内容）
本アプリは、次の機能を基本無料で提供する。

1. PDFの閲覧、書き込み、注釈、検索
2. 学習時間・学習内容の記録、および学習状況のグラフ表示
3. 課題・やるべきことの管理（Todo）
4. 学習時間に応じたレベルアップ等の機能
5. 学習時間ランキング（すたらん）、ルーム、フォロワーなど、他のユーザーと交流する機能
6. ユーザーが許可した場合のGoogleドライブとの連携
7. その他、運営者が追加する機能

第4条（利用料金）
本アプリは基本無料で提供する。ただし、運営者が一部の機能を有料とする場合は、事前にその内容および料金を本アプリまたはウェブサイト上で知らせる。

第5条（アカウントの管理）
ユーザーは、自己のGoogleアカウントおよび端末を、自己の責任で管理するものとする。

第6条（Googleアカウントおよび外部サービスとの連携）
1. 本アプリは、ユーザーが許可した範囲でのみ、Googleアカウントの情報（メールアドレス、氏名、プロフィール画像）およびGoogleドライブ上の、ユーザーが選択したファイルを利用する。
2. ユーザーは、Googleアカウントの設定画面から、いつでも本アプリへの許可を取り消すことができる。
3. 運営者は、Google、Supabase、Vercelなどの外部サービスを利用して本アプリを運営している。外部サービスの利用条件は、各提供者の定めるところによる。

第7条（禁止事項）
ユーザーは、次の行為をしてはならない。

1. 法令または公序良俗に違反する行為
2. 本アプリのサーバーやネットワークに過度な負荷をかける行為
3. 不正アクセス、またはその試み
4. 本アプリのスクレイピング、リバースエンジニアリング、その他の方法による解析
5. 他者の権利（知的財産権、プライバシー、名誉など）を侵害する行為
6. 本アプリの交流機能（ランキング、ルーム、フォロワー等）を通じて、他のユーザーに嫌がらせをし、または迷惑をかける行為
7. 本アプリを、運営者が意図しない方法で利用し、または第三者に不正に利用させる行為
8. 虚偽の学習記録を登録するなど、他のユーザーを欺く行為
9. その他、運営者が不適切と判断する行為

第8条（知的財産権）
本アプリおよびこれに付随する一切のコンテンツに関する知的財産権は、運営者または正当な権利者に帰属する。ユーザーは、これらを運営者の許可なく複製、転載、再配布してはならない。

第9条（ユーザーのデータおよび公開される情報）
1. ユーザーが本アプリに登録した学習記録その他のデータ（以下「ユーザーデータ」という。）の権利は、ユーザーに帰属する。
2. 運営者は、本アプリの提供・維持・改善に必要な範囲でのみ、ユーザーデータを利用する。
3. ランキング、ルーム、フォロワーなどの交流機能では、ユーザー名、学習時間その他の情報が、他のユーザーに表示される場合がある。ユーザーは、これに同意のうえ利用するものとする。
4. ユーザーデータの取扱いは、別に定めるプライバシーポリシーに従う。

第10条（データの保存）
運営者は、ユーザーデータの保存に努めるが、その消失・破損が生じないことを保証しない。重要なデータは、ユーザー自身でも控えを取ること。

第11条（サービスの変更・中断・終了）
1. 運営者は、保守、障害、不可抗力その他の事情により、事前の通知なく本アプリの全部または一部を中断することがある。
2. 運営者は、必要に応じて、本アプリの内容を変更し、または提供を終了することがある。終了する場合は、可能な限り事前に本アプリまたはウェブサイト上で知らせる。

第12条（利用の停止および退会）
1. 運営者は、ユーザーが本規約に違反した場合、事前の通知なく、そのユーザーの利用を停止することがある。
2. ユーザーは、第17条の連絡先に申し出ることにより、いつでも退会し、自己のデータの削除を求めることができる。

第13条（免責）
1. 本アプリは現状有姿で提供する。運営者は、本アプリの正確性、有用性、継続性、エラーがないことについて保証しない。
2. 本アプリの利用により学習の成果が得られることを、運営者は保証しない。
3. 交流機能を通じたユーザー間のトラブルについて、運営者は責任を負わない。ただし、運営者が必要と判断した場合は、対応を行うことがある。
4. 本アプリの中断、変更、終了、またはユーザーデータの消失・破損によってユーザーに生じた損害について、運営者は責任を負わない。
5. 運営者に故意または重大な過失がある場合には、本条および次条の免責・責任制限は適用されない。

第14条（責任の制限）
運営者がユーザーに対して損害賠償責任を負う場合でも、その範囲は、ユーザーに現実に生じた通常の直接損害に限る。

第15条（規約の変更）
1. 運営者は、必要に応じて本規約を変更することがある。
2. 変更後の規約は、本アプリまたはウェブサイトに掲載した時点から効力を生じる。重要な変更を行う場合は、掲載を通じて事前に知らせる。
3. 変更後に本アプリを利用した場合、ユーザーは変更後の規約に同意したものとみなす。

第16条（準拠法・管轄）
本規約は日本法に準拠する。本アプリに関して紛争が生じた場合は、民事訴訟法に定める管轄裁判所を第一審の裁判所とする。

第17条（連絡先）
本規約および本アプリに関する問い合わせは、次の連絡先に行うこと。
運営者：Mercury運営局
メール：admin.mercury@gmail.com
`;

export const TERMS_OF_SERVICE_EN = `
Mercury Terms of Service

Established: October 5, 2026

Article 1 (Application)
1. These Terms of Service (the "Terms") set out the conditions for using the study management app "Mercury" (the "App") provided by the operator.
2. These Terms apply to everyone who uses the App ("Users").
3. Notices, guidelines, and other rules separately established by the operator within the App form part of these Terms. In the event of a conflict, those rules take precedence.

Article 2 (Starting Use)
1. Users shall sign in with a Google account and agree to these Terms before starting to use the App.
2. By signing in and starting to use the App, Users are deemed to have agreed to these Terms.
3. Minors must obtain consent from a parent or guardian before using the App.

Article 3 (Services)
The App provides the following features free of charge as its basic offering.

1. PDF viewing, writing, annotation, and search
2. Recording study time and study content, and displaying study progress in graphs
3. Managing assignments and tasks (Todo)
4. Features such as leveling up based on study time
5. Features for interacting with other Users, such as study time rankings (Sutaran), rooms, and followers
6. Google Drive integration when authorized by the User
7. Other features added by the operator

Article 4 (Fees)
The App is basically free to use. If the operator makes certain features paid, their details and fees will be announced in advance within the App or on the website.

Article 5 (Account Management)
Users are responsible for managing their own Google accounts and devices.

Article 6 (Google Accounts and External Service Integration)
1. The App uses Google account information (email address, name, and profile image) and files selected by the User on Google Drive only within the scope authorized by the User.
2. Users may revoke permissions granted to the App at any time through their Google account settings.
3. The operator uses external services such as Google, Supabase, and Vercel to operate the App. The terms of each external service are determined by its provider.

Article 7 (Prohibited Conduct)
Users must not engage in any of the following acts.

1. Acts that violate laws or public order and morals
2. Placing excessive load on the App's servers or networks
3. Unauthorized access or attempts to gain unauthorized access
4. Analyzing the App through scraping, reverse engineering, or other methods
5. Infringing the rights of others, including intellectual property rights, privacy, and reputation
6. Harassing or causing inconvenience to other Users through the App's interaction features, including rankings, rooms, and followers
7. Using the App in ways not intended by the operator or allowing third parties to use it improperly
8. Deceiving other Users, such as by registering false study records
9. Other acts deemed inappropriate by the operator

Article 8 (Intellectual Property Rights)
Intellectual property rights in the App and all associated content belong to the operator or the rightful rights holders. Users must not copy, republish, or redistribute them without the operator's permission.

Article 9 (User Data and Publicly Displayed Information)
1. Rights in study records and other data registered by Users in the App ("User Data") belong to the Users.
2. The operator uses User Data only to the extent necessary to provide, maintain, and improve the App.
3. Interaction features such as rankings, rooms, and followers may display usernames, study time, and other information to other Users. Users shall use these features with their consent to such display.
4. User Data is handled in accordance with the separately established Privacy Policy.

Article 10 (Data Storage)
The operator endeavors to store User Data but does not guarantee that it will not be lost or corrupted. Users should also keep their own copies of important data.

Article 11 (Service Changes, Interruptions, and Termination)
1. The operator may interrupt all or part of the App without prior notice due to maintenance, failures, force majeure, or other circumstances.
2. The operator may change the App or terminate its provision as necessary. When terminating the service, the operator will give advance notice within the App or on the website whenever possible.

Article 12 (Suspension of Use and Withdrawal)
1. If a User violates these Terms, the operator may suspend that User's use without prior notice.
2. Users may withdraw and request deletion of their data at any time by contacting the address specified in Article 17.

Article 13 (Disclaimer)
1. The App is provided as is. The operator does not guarantee its accuracy, usefulness, continuity, or freedom from errors.
2. The operator does not guarantee that using the App will produce learning outcomes.
3. The operator is not responsible for disputes between Users arising through interaction features. However, the operator may take action when it considers it necessary.
4. The operator is not responsible for damages incurred by Users due to interruption, change, or termination of the App, or loss or corruption of User Data.
5. The disclaimers and limitations of liability in this Article and the following Article do not apply in cases of the operator's intentional misconduct or gross negligence.

Article 14 (Limitation of Liability)
Even when the operator is liable to a User for damages, liability is limited to ordinary direct damages actually incurred by that User.

Article 15 (Changes to the Terms)
1. The operator may change these Terms as necessary.
2. Revised Terms take effect when posted within the App or on the website. Important changes will be announced in advance through such posting.
3. Users who use the App after the changes are deemed to have agreed to the revised Terms.

Article 16 (Governing Law and Jurisdiction)
These Terms are governed by Japanese law. In the event of a dispute relating to the App, the court having jurisdiction under the Code of Civil Procedure shall be the court of first instance.

Article 17 (Contact)
Inquiries regarding these Terms and the App should be directed to the following contact.
Operator: Mercury Administration Office
Email: admin.mercury@gmail.com
`;
